name: TOB_fe

on:
  schedule:
    # Runs every 2 hours from 10:30 pm ist to 4:30 am ist
    - cron: '0 17-23/2 * * *'
    # # Runs every 2 hours from 6:30 pm ist to 4:30 am ist
    # - cron: '0 13-23/2 * * *'

jobs:
  pull-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        run: |
          git clone -b main https://sarva-suvidhaen:${{ secrets.PERSONAL_TOKEN  }}@github.com/s2pl/TrainOnBoarding_FE.git
          
        # uses: actions/checkout@v2
        # with:
        #   repository: s2pl/SwachhStations_FE
        #   token: ${{ secrets.PERSONAL_TOKEN  }}

      - name: Add source repository as upstream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          cd TrainOnBoarding_FE
          git remote add upstream https://sarva-suvidhaen:${{ secrets.PERSONAL_TOKEN  }}@github.com/sarva-suvidhaen/tob-fe.git

      - name: Push to destination repository
        run: |
          cd TrainOnBoarding_FE
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git push -f upstream main

      # - name: Update Backend 1
      #   run: |
      #     curl https://redeploy-cmsapi.suvidhaen.com/hooks/rerun-each-deploy-script

      # - name: Update Backend 2
      #   run: |
      #     curl https://redeploy-cmsapi2.suvidhaen.com/hooks/rerun-each-deploy-script

      # - name: Send mail
      #   if: always()
      #   uses: dawidd6/action-send-mail@v2
      #   with:
      #     # mail server settings
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     # user credentials
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     # email subject
      #     subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      #     # email body as text
      #     body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      #     # comma-separated string, send email to
      #     to: atul.nitt.cse@gmail.com,tomarm698@gmail.com,mohanakhil329@gmail.com
      #     # from email name
      #     from: github action